//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentHost.AgentControlServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.comodo.com/esm/testlabs/asyncperformancetest", ConfigurationName="AgentControlServiceReference.AgentsControlService", CallbackContract=typeof(AgentHost.AgentControlServiceReference.AgentsControlServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface AgentsControlService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentsControlService/" +
            "Register")]
        void Register();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentsControlService/" +
            "Register")]
        System.Threading.Tasks.Task RegisterAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgentsControlServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentsControlService/" +
            "Initialize")]
        void Initialize(long[] ids);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentsControlService/" +
            "SetConnectionsCount")]
        void SetConnectionsCount(int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgentsControlServiceChannel : AgentHost.AgentControlServiceReference.AgentsControlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgentsControlServiceClient : System.ServiceModel.DuplexClientBase<AgentHost.AgentControlServiceReference.AgentsControlService>, AgentHost.AgentControlServiceReference.AgentsControlService {
        
        public AgentsControlServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AgentsControlServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AgentsControlServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AgentsControlServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AgentsControlServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Register() {
            base.Channel.Register();
        }
        
        public System.Threading.Tasks.Task RegisterAsync() {
            return base.Channel.RegisterAsync();
        }
    }
}
