//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentHost.AgentServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.comodo.com/esm/testlabs/asyncperformancetest", ConfigurationName="AgentServiceReference.AgentService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface AgentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentService/Handshak" +
            "e", ReplyAction="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentService/Handshak" +
            "eResponse")]
        void Handshake(long agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentService/Handshak" +
            "e", ReplyAction="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentService/Handshak" +
            "eResponse")]
        System.Threading.Tasks.Task HandshakeAsync(long agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentService/DoOperat" +
            "ion", ReplyAction="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentService/DoOperat" +
            "ionResponse")]
        void DoOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentService/DoOperat" +
            "ion", ReplyAction="http://schemas.comodo.com/esm/testlabs/asyncperformancetest/AgentService/DoOperat" +
            "ionResponse")]
        System.Threading.Tasks.Task DoOperationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgentServiceChannel : AgentHost.AgentServiceReference.AgentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgentServiceClient : System.ServiceModel.ClientBase<AgentHost.AgentServiceReference.AgentService>, AgentHost.AgentServiceReference.AgentService {
        
        public AgentServiceClient() {
        }
        
        public AgentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Handshake(long agentId) {
            base.Channel.Handshake(agentId);
        }
        
        public System.Threading.Tasks.Task HandshakeAsync(long agentId) {
            return base.Channel.HandshakeAsync(agentId);
        }
        
        public void DoOperation() {
            base.Channel.DoOperation();
        }
        
        public System.Threading.Tasks.Task DoOperationAsync() {
            return base.Channel.DoOperationAsync();
        }
    }
}
